### ISSUE TITLE
Add system components

### ISSUE THREAD

**Issue by oubiwann** [hexagram30/hexagramMUSH#2]
* [x] configuration
* [x] logging
* [x] terminal
  * [x] telnet
  * [x] secure telnet (or ssh)
  * [ ] ~secure Clojure REPL~
* [x] database
* [ ] an HTTP server 
     * [ ] ~serve static HTML for help files and docs~ (see #10)
     * [ ] ~dynamic HTML for system status~ (see #11)
     * [ ] REST API (use jarfile plugins for other components in other projects and assemble - see #12)
